# Generated by Django 2.2 on 2020-10-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0003_sentiment_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
