# Generated by Django 2.2 on 2020-10-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0004_auto_20201029_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='probabilities',
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
