# Generated by Django 2.2 on 2020-10-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0005_auto_20201029_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='country',
            field=models.CharField(blank=True, choices=[('United States of America', 'United States of America'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Europe', 'Europe'), ('Japan', 'Japan'), ('South Korea', 'South Korea')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
