# Generated by Django 2.2 on 2020-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0007_auto_20201029_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='results',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
