# Generated by Django 2.2 on 2020-10-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0008_auto_20201029_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentiment',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
